INSERT INTO users (id, name, email) VALUES (1, 'name_1', 'email_1@example.com');
INSERT INTO users (id, name, email) VALUES (2, 'name_2', 'email_2@example.com');
INSERT INTO users (id, name, email) VALUES (3, 'name_3', 'email_3@example.com');
INSERT INTO users (id, name, email) VALUES (4, 'name_4', 'email_4@example.com');
INSERT INTO users (id, name, email) VALUES (5, 'name_5', 'email_5@example.com');
INSERT INTO users (id, name, email) VALUES (6, 'name_6', 'email_6@example.com');
INSERT INTO users (id, name, email) VALUES (7, 'name_7', 'email_7@example.com');
INSERT INTO users (id, name, email) VALUES (8, 'name_8', 'email_8@example.com');
INSERT INTO users (id, name, email) VALUES (9, 'name_9', 'email_9@example.com');
INSERT INTO users (id, name, email) VALUES (10, 'name_10', 'email_10@example.com');
INSERT INTO orders (id, user_id) VALUES (1, 8);
INSERT INTO orders (id, user_id) VALUES (2, 7);
INSERT INTO orders (id, user_id) VALUES (3, 8);
INSERT INTO orders (id, user_id) VALUES (4, 2);
INSERT INTO orders (id, user_id) VALUES (5, 10);
INSERT INTO orders (id, user_id) VALUES (6, 1);
INSERT INTO orders (id, user_id) VALUES (7, 6);
INSERT INTO orders (id, user_id) VALUES (8, 4);
INSERT INTO orders (id, user_id) VALUES (9, 3);
INSERT INTO orders (id, user_id) VALUES (10, 4);
